"""empty message

Revision ID: 0caa3600fac0
Revises: 0362fcc283dc
Create Date: 2022-08-24 23:35:36.617729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0caa3600fac0'
down_revision = '0362fcc283dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Categoria',
    sa.Column('categorias_id', sa.Integer(), nullable=False),
    sa.Column('proveedores_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categorias_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['proveedores_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('categorias_id', 'proveedores_id')
    )
    op.drop_table('tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('categorias_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('proveedores_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['categorias_id'], ['categoria.id'], name='tags_categorias_id_fkey'),
    sa.ForeignKeyConstraint(['proveedores_id'], ['proveedores.id'], name='tags_proveedores_id_fkey'),
    sa.PrimaryKeyConstraint('categorias_id', 'proveedores_id', name='tags_pkey')
    )
    op.drop_table('Categoria')
    # ### end Alembic commands ###
