"""empty message

Revision ID: 7689ef5b203f
Revises: 923521f24cba
Create Date: 2022-08-25 18:47:45.413339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7689ef5b203f'
down_revision = '923521f24cba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proveedores', 'solvente',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proveedores', 'solvente',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
