"""empty message

Revision ID: 90f0afdba514
Revises: c06e1582bb7b
Create Date: 2022-08-24 23:14:38.219302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90f0afdba514'
down_revision = 'c06e1582bb7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ranking', sa.Column('id_usuario', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ranking', 'user', ['id_usuario'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ranking', type_='foreignkey')
    op.drop_column('ranking', 'id_usuario')
    # ### end Alembic commands ###
