"""empty message

Revision ID: 923521f24cba
Revises: 0caa3600fac0
Create Date: 2022-08-25 11:30:10.444026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '923521f24cba'
down_revision = '0caa3600fac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
