"""empty message

Revision ID: 992984ff9ef7
Revises: c3434b35eceb
Create Date: 2022-08-30 23:15:38.803635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '992984ff9ef7'
down_revision = 'c3434b35eceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proveedores', 'solvente')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proveedores', sa.Column('solvente', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
