"""empty message

Revision ID: a3f85d7544be
Revises: 
Create Date: 2022-08-31 22:57:17.383375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3f85d7544be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion_categoria', sa.String(length=300), nullable=False),
    sa.Column('descripcion_subcategoria', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('typeuser', sa.String(length=1), nullable=False),
    sa.Column('indentificacion', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('photo', sa.String(length=1000), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('indentificacion'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('personacontacto', sa.String(length=120), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ranking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('calificacion', sa.Integer(), nullable=True),
    sa.Column('comentario', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Categoria',
    sa.Column('categorias_id', sa.Integer(), nullable=False),
    sa.Column('proveedores_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categorias_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['proveedores_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('categorias_id', 'proveedores_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Categoria')
    op.drop_table('ranking')
    op.drop_table('proveedores')
    op.drop_table('user')
    op.drop_table('categoria')
    # ### end Alembic commands ###
