"""empty message

Revision ID: a45ea18f26ff
Revises: 87ffd37b3ffc
Create Date: 2022-08-26 21:56:32.518667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a45ea18f26ff'
down_revision = '87ffd37b3ffc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ranking_id_categoria_fkey', 'ranking', type_='foreignkey')
    op.drop_constraint('ranking_id_ranking_fkey', 'ranking', type_='foreignkey')
    op.drop_column('ranking', 'id_categoria')
    op.drop_column('ranking', 'id_ranking')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ranking', sa.Column('id_ranking', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ranking', sa.Column('id_categoria', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('ranking_id_ranking_fkey', 'ranking', 'proveedores', ['id_ranking'], ['id'])
    op.create_foreign_key('ranking_id_categoria_fkey', 'ranking', 'categoria', ['id_categoria'], ['id'])
    # ### end Alembic commands ###
