"""empty message

Revision ID: c06e1582bb7b
Revises: 9632c784faa6
Create Date: 2022-08-24 22:53:49.050531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c06e1582bb7b'
down_revision = '9632c784faa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categoria', sa.Column('descripcion_subcategoria', sa.String(length=300), nullable=False))
    op.drop_constraint('categoria_descrion_subcategoria_key', 'categoria', type_='unique')
    op.create_unique_constraint(None, 'categoria', ['descripcion_subcategoria'])
    op.drop_column('categoria', 'descrion_subcategoria')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categoria', sa.Column('descrion_subcategoria', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'categoria', type_='unique')
    op.create_unique_constraint('categoria_descrion_subcategoria_key', 'categoria', ['descrion_subcategoria'])
    op.drop_column('categoria', 'descripcion_subcategoria')
    # ### end Alembic commands ###
