"""empty message

Revision ID: c3434b35eceb
Revises: 44fc0d930e44
Create Date: 2022-08-30 11:37:27.011107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3434b35eceb'
down_revision = '44fc0d930e44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('categoria_descripcion_categoria_key', 'categoria', type_='unique')
    op.drop_constraint('categoria_descripcion_subcategoria_key', 'categoria', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('categoria_descripcion_subcategoria_key', 'categoria', ['descripcion_subcategoria'])
    op.create_unique_constraint('categoria_descripcion_categoria_key', 'categoria', ['descripcion_categoria'])
    # ### end Alembic commands ###
