"""empty message

Revision ID: c9ac469af984
Revises: e4df37facb5c
Create Date: 2022-08-31 01:35:56.717144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9ac469af984'
down_revision = 'e4df37facb5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ranking', 'calificacion',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ranking', 'calificacion',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
