"""empty message

Revision ID: e4df37facb5c
Revises: 0d12568ee90d
Create Date: 2022-08-31 00:19:08.362910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4df37facb5c'
down_revision = '0d12568ee90d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('proveedores_descripcion_key', 'proveedores', type_='unique')
    op.drop_constraint('proveedores_personacontacto_key', 'proveedores', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('proveedores_personacontacto_key', 'proveedores', ['personacontacto'])
    op.create_unique_constraint('proveedores_descripcion_key', 'proveedores', ['descripcion'])
    # ### end Alembic commands ###
