"""empty message

Revision ID: fe014544d97d
Revises: 60e21dd77385
Create Date: 2022-08-30 23:26:35.801194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe014544d97d'
down_revision = '60e21dd77385'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'letraidentificacion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('letraidentificacion', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
